version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: ".eslintrc.json"
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_patterns:
  - "assets/scripts/vendor/*.js"
  - "test/integration/smoke.spec.js"
  - "**/__tests__"
  - "**/__mocks__"
